; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool on Tue Oct 30 2018 18:17:49 GMT-0700 (Pacific Daylight Time)
M561                ; clear any bed transform
M98 Pdeployprobe.g  ; deploy mechanical Z probe
; Probe the bed at 5 points
G30 P0 X15 Y15 H0 Z-99999
G30 P1 X15 Y285 H0 Z-99999
G30 P2 X285 Y285 H0 Z-99999
G30 P3 X285 Y15 H0 Z-99999
G30 P4 X150 Y150 H0 Z-99999 S
M98 Pretractprobe.g ; retract mechanical Z probe