; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool on Tue Oct 30 2018 18:17:49 GMT-0700 (Pacific Daylight Time)
; Wait for set temperatures to be reached
M116 P0